on:
  pull_request:
    branches:
      - master
      - continuous_integration
    
name: R_styler

jobs:
  R_styler:
    runs-on: macOS-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/pr-fetch@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: r-lib/actions/setup-r@master
      
      - name: Install dependencies
        run: Rscript -e 'install.packages("styler")'
        
      - name: Style
        run: Rscript -e 'styler::style_pkg()'
